description = "通过交互或提供的原则输入，创建或更新项目宪章，并确保所有依赖模板保持同步。"

prompt = """
---
description: 通过交互或提供的原则输入，创建或更新项目宪章，并确保所有依赖模板保持同步。
---

## 用户输入

```text
$ARGUMENTS
```

在继续之前，若用户输入不为空，你必须考虑它。

## 大纲

你正在更新位于 `.specify/memory/constitution.md` 的项目宪章。该文件是一个 TEMPLATE，包含使用方括号的占位符（例如 `[PROJECT_NAME]`、`[PRINCIPLE_1_NAME]`）。你的工作是：(a) 收集/推导具体值，(b) 精准填充模板，(c) 将任何修订同步传播到依赖制品。

遵循以下执行流程：

1. 加载位于 `.specify/memory/constitution.md` 的现有宪章模板。
   - 识别所有形如 `[ALL_CAPS_IDENTIFIER]` 的占位符。
   **重要**：用户可能要求的原则数量与模板中的数量不同。若指定了数量，请遵循该数量并沿用通用模板。你将据此更新文档。

2. 收集/推导占位符的值：
   - 若用户输入（会话）提供了某值，则使用该值。
   - 否则从现有仓库上下文推断（README、docs、若嵌入则参考先前宪章版本）。
   - 对治理日期：`RATIFICATION_DATE` 为原始采纳日期（若未知请询问或标记 TODO），`LAST_AMENDED_DATE` 如发生变更则为今日，否则保持原值。
   - `CONSTITUTION_VERSION` 必须按语义化版本规则递增：
     * MAJOR：向后不兼容的治理/原则移除或重新定义。
     * MINOR：新增原则/章节或实质扩展指导。
     * PATCH：澄清、措辞、拼写修正、非语义性优化。
   - 若版本提升类型不明确，先提出理由再最终确定。

3. 起草更新后的宪章内容：
   - 用具体文本替换每个占位符（不应残留方括号 token，除非项目选择有意保留的模板槽位——需明确说明保留理由）。
   - 保留标题层级，已替换的注释可移除，除非仍能提供澄清性指导。
   - 确保每个 Principle 章节包含：简洁名称行、概述不可协商规则的段落（或列表）、在非显而易见时给出明确 rationale。
   - 确保 Governance 章节列出修订流程、版本策略与合规性审查预期。

4. 一致性传播检查清单（将先前清单转化为有效校验）：
   - 读取 `.specify/templates/plan-template.md`，确保其中的 "Constitution Check" 或规则与更新后的原则对齐。
   - 读取 `.specify/templates/spec-template.md` 的范围/Requirements 对齐情况——若宪章增删了强制章节或约束则同步更新。
   - 读取 `.specify/templates/tasks-template.md`，确保任务分类反映新增或移除的原则驱动任务类型（例如 observability、versioning、testing discipline）。
   - 读取 `.specify/templates/commands/*.md`（包含本文件），验证不再出现过时引用（例如仅限某 Agent 名如 CLAUDE），在需要通用指导时保持通用。
   - 读取运行时指导文档（例如 `README.md`、`docs/quickstart.md` 或若存在的 Agent 专用指导文件）。更新受原则变化影响的引用。

5. 生成同步影响报告（在更新后以 HTML 注释形式置于宪章文件顶部）：
   - Version 变更：old → new
   - 修改的原则列表（旧标题 → 新标题，若重命名）
   - 新增章节
   - 移除章节
   - 需要更新的模板（✅ 已更新 / ⚠ 待处理）及文件路径
   - 若有有意保留的占位符，列出后续 TODO。

6. 输出前校验：
   - 不应残留未解释的方括号 token。
   - 版本行与报告一致。
   - 日期为 ISO 格式 YYYY-MM-DD。
   - 原则表述具备宣告性、可测试，避免模糊语言（将 "should" 以 MUST/SHOULD 的 rationale 进行替换）。

7. 将完成的宪章写回 `.specify/memory/constitution.md`（覆盖写入）。

8. 向用户输出总结：
   - 新版本与版本提升的理由
   - 标记需要人工跟进的文件
   - 建议的提交信息（例如 `docs: amend constitution to vX.Y.Z (principle additions + governance update)`）

格式与样式要求：
- 使用与模板相同的 Markdown 标题（不要提升/降低层级）。
- 对较长 rationale 进行换行以保持可读性（理想 <100 字符），但不要为了换行而破坏表达自然性。
- 章节之间保持单个空行。
- 避免尾随空格。

若用户仅提供部分更新（例如仅修改一个 Principle），仍需执行校验与版本决策步骤。

若缺失关键信息（例如确实未知的 ratification date），插入 `TODO(<FIELD_NAME>): explanation`，并在 Sync Impact Report 的 deferred 项中包含。

不要创建新模板；始终对现有 `.specify/memory/constitution.md` 文件进行操作。
"""
